#!/usr/bin/env bash
# Put buzz-backend-cloud on PATH (~/.local/bin) so Desktop shows Run on → cloud,
# and install LaunchAgent xyz.block.buzz.cloud-sync.
# Desktop globs buzz-backend-*; do not install a .py with that prefix (id would
# become cloud.py). Finder-launched Desktop has a minimal PATH, so this wrapper
# bakes in python3 / Homebrew / gcloud directories.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root="$(cd "$here/.." && pwd)"
bin="${HOME}/.local/bin"
agents_dir="${HOME}/Library/Application Support/xyz.block.buzz.app/agents"
launch_agents="${HOME}/Library/LaunchAgents"
label="xyz.block.buzz.cloud-sync"
plist="${launch_agents}/${label}.plist"
uid="$(id -u)"

mkdir -p "$bin" "$agents_dir" "$launch_agents"

is_placeholder() {
  local v="${1:-}"
  [[ -z "$v" || "$v" == "-" || "$v" == "your-gcp-project" || "$v" == "wss://your-community.communities.buzz.xyz" ]]
}

load_env_file() {
  local f="$1"
  [[ -f "$f" ]] || return 0
  while IFS= read -r line || [[ -n "$line" ]]; do
    line="${line%$'\r'}"
    [[ -z "$line" || "$line" == \#* ]] && continue
    if [[ "$line" =~ ^([A-Za-z_][A-Za-z0-9_]*)=(.*)$ ]]; then
      local key="${BASH_REMATCH[1]}"
      local val="${BASH_REMATCH[2]}"
      val="${val#\"}"
      val="${val%\"}"
      val="${val#\'}"
      val="${val%\'}"
      if [[ -z "${!key:-}" ]]; then
        export "$key=$val"
      fi
    fi
  done < "$f"
}

load_env_file "$root/.env"
load_env_file "$root/infra/config.env"

: "${BUZZ_GCP_PROJECT:=${GCP_PROJECT:-${GOOGLE_CLOUD_PROJECT:-your-gcp-project}}}"
: "${BUZZ_GCP_ZONE:=${GCP_ZONE:-us-central1-a}}"
: "${BUZZ_GCP_INSTANCE:=${LISTENER_INSTANCE:-buzz-listener}}"
: "${BUZZ_RELAY_URL:=${RELAY_URL:-wss://your-community.communities.buzz.xyz}}"
export BUZZ_GCP_PROJECT BUZZ_GCP_ZONE BUZZ_GCP_INSTANCE BUZZ_RELAY_URL

find_python() {
  local candidate
  for candidate in \
      "${PYTHON:-}" \
      "$(command -v python3 2>/dev/null || true)" \
      /opt/homebrew/bin/python3 \
      /usr/local/bin/python3 \
      "${HOME}/.local/bin/python3"; do
    [[ -n "$candidate" && -x "$candidate" ]] || continue
    # Reject the macOS /usr/bin/python3 stub that only prompts for Xcode.
    if "$candidate" -c 'import sys; raise SystemExit(0 if sys.version_info >= (3, 10) else 1)' 2>/dev/null; then
      printf '%s\n' "$candidate"
      return 0
    fi
  done
  return 1
}

find_gcloud() {
  local candidate
  for candidate in \
      "$(command -v gcloud 2>/dev/null || true)" \
      /opt/homebrew/bin/gcloud \
      /usr/local/bin/gcloud \
      "${HOME}/google-cloud-sdk/bin/gcloud" \
      /opt/homebrew/share/google-cloud-sdk/bin/gcloud \
      /usr/local/google-cloud-sdk/bin/gcloud; do
    [[ -n "$candidate" && -x "$candidate" ]] || continue
    printf '%s\n' "$candidate"
    return 0
  done
  return 1
}

python="$(find_python)" || {
  echo "python3 >= 3.10 not found. Install CPython (python.org or brew install python) and re-run." >&2
  exit 1
}
gcloud="$(find_gcloud)" || {
  echo "gcloud not found. Install the Google Cloud SDK: https://cloud.google.com/sdk/docs/install" >&2
  exit 1
}

impl="${bin}/buzz_cloud_impl.py"
sync_impl="${bin}/buzz_cloud_sync.py"
wrapper="${bin}/buzz-backend-cloud"
gcloud_dir="$(cd "$(dirname "$gcloud")" && pwd)"
python_dir="$(cd "$(dirname "$python")" && pwd)"

cp -f "${here}/buzz-backend-cloud.py" "$impl"
rm -f "${bin}/buzz-backend-cloud.py" "${bin}/buzz-backend-cloud.sh"

listener_util="${root}/listener/agentutil.py"
if [[ ! -f "$listener_util" ]]; then
  listener_util="${here}/agentutil.py"
fi
if [[ -f "$listener_util" ]]; then
  cp -f "$listener_util" "${bin}/agentutil.py"
fi
listener_nostr="${root}/listener/nostrutil.py"
if [[ ! -f "$listener_nostr" ]]; then
  listener_nostr="${here}/nostrutil.py"
fi
if [[ -f "$listener_nostr" ]]; then
  cp -f "$listener_nostr" "${bin}/nostrutil.py"
fi
cp -f "${here}/buzz-cloud-sync.py" "$sync_impl"

path_extra="${python_dir}:${bin}:${gcloud_dir}:/opt/homebrew/bin:/usr/local/bin:${HOME}/.local/bin:/usr/bin:/bin"

cat > "$wrapper" <<EOF
#!/bin/bash
# Generated by macos/install-path.sh. Desktop execs this path in place.
export PATH="${path_extra}:\${PATH}"
export BUZZ_GCP_PROJECT="${BUZZ_GCP_PROJECT}"
export BUZZ_GCP_ZONE="${BUZZ_GCP_ZONE}"
export BUZZ_GCP_INSTANCE="${BUZZ_GCP_INSTANCE}"
export BUZZ_RELAY_URL="${BUZZ_RELAY_URL}"
exec "${python}" "${impl}" "\$@"
EOF
chmod 755 "$wrapper"

xml_escape() {
  local s="$1"
  s="${s//&/&amp;}"
  s="${s//</&lt;}"
  s="${s//>/&gt;}"
  s="${s//\"/&quot;}"
  printf '%s' "$s"
}

# Desktop always scans ~/.local/bin. Still put it on the login PATH for CLI use.
marker="# buzz-backend-cloud"
zprofile="${HOME}/.zprofile"
if [[ ! -f "$zprofile" ]] || ! grep -Fq "$marker" "$zprofile"; then
  {
    echo ""
    cat <<'ZPROFILE'
# buzz-backend-cloud
case ":$PATH:" in *:"$HOME/.local/bin":*) ;; *) export PATH="$HOME/.local/bin:$PATH" ;; esac
ZPROFILE
  } >> "$zprofile"
  echo "Added ${bin} to PATH in ~/.zprofile. Restart Buzz Desktop so Run on → cloud appears."
else
  echo "Already on PATH: ${bin}"
  echo "Restart Buzz Desktop so it picks up ${wrapper}."
fi
echo "Provider id: cloud (default). New agents should Run on → cloud; stop any local Goose copy."

stop_leftovers() {
  launchctl bootout "gui/${uid}/${label}" >/dev/null 2>&1 || true
  # Do not pkill this installer. Match the installed sidecar and IAP tunnels.
  pkill -f "${sync_impl}" >/dev/null 2>&1 || true
  pkill -f 'buzz_cloud_sync[.]py|buzz-cloud-sync[.]py' >/dev/null 2>&1 || true
  pkill -f 'start-iap-tunnel.*buzz-listener' >/dev/null 2>&1 || true
  pkill -f 'compute ssh.*buzz-listener.*8743' >/dev/null 2>&1 || true
  sleep 0.3
}

stop_leftovers

log_path="${agents_dir}/cloud-sync.log"
py_xml="$(xml_escape "$python")"
sync_xml="$(xml_escape "$sync_impl")"
bin_xml="$(xml_escape "$bin")"
home_xml="$(xml_escape "$HOME")"
path_xml="$(xml_escape "$path_extra")"
project_xml="$(xml_escape "$BUZZ_GCP_PROJECT")"
zone_xml="$(xml_escape "$BUZZ_GCP_ZONE")"
instance_xml="$(xml_escape "$BUZZ_GCP_INSTANCE")"
relay_xml="$(xml_escape "$BUZZ_RELAY_URL")"
log_xml="$(xml_escape "$log_path")"
cat > "$plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${label}</string>
  <key>ProgramArguments</key>
  <array>
    <string>${py_xml}</string>
    <string>${sync_xml}</string>
  </array>
  <key>WorkingDirectory</key>
  <string>${bin_xml}</string>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <dict>
    <key>SuccessfulExit</key>
    <false/>
  </dict>
  <key>ThrottleInterval</key>
  <integer>10</integer>
  <key>ProcessType</key>
  <string>Background</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>HOME</key>
    <string>${home_xml}</string>
    <key>PATH</key>
    <string>${path_xml}</string>
    <key>BUZZ_GCP_PROJECT</key>
    <string>${project_xml}</string>
    <key>BUZZ_GCP_ZONE</key>
    <string>${zone_xml}</string>
    <key>BUZZ_GCP_INSTANCE</key>
    <string>${instance_xml}</string>
    <key>BUZZ_RELAY_URL</key>
    <string>${relay_xml}</string>
  </dict>
  <key>StandardOutPath</key>
  <string>${log_xml}</string>
  <key>StandardErrorPath</key>
  <string>${log_xml}</string>
</dict>
</plist>
EOF

if ! launchctl bootstrap "gui/${uid}" "$plist" >/dev/null 2>&1; then
  launchctl kickstart -k "gui/${uid}/${label}" >/dev/null 2>&1 || true
fi
launchctl enable "gui/${uid}/${label}" >/dev/null 2>&1 || true
launchctl kickstart -k "gui/${uid}/${label}" >/dev/null 2>&1 || true

echo "BuzzCloudSync LaunchAgent ${label} is running (${python}). One instance; IAP tunnel is silent."
if is_placeholder "$BUZZ_GCP_PROJECT"; then
  echo "warning: BUZZ_GCP_PROJECT is unset. Fill .env and re-run ./macos/install-path.sh" >&2
fi
echo "If macOS asks to use the Keychain item for buzz-desktop, choose Always Allow so the sidecar can read nsecs."
